// Generated by Text-to-CAD: o-ring inner diameter of 10 inches, outer diameter of 12 inches, thickness of 0.5 inches
// Define constants in inches
innerDiameter = 10.0
outerDiameter = 12.0
thickness = 0.5
// define a plane
plane000 = {
  plane: {
    origin: [0.000000, 0.000000, 0.000000],
    xAxis: [1.000000, 0.000000, 0.000000],
    yAxis: [0.000000, 1.000000, 0.000000],
    zAxis: [0.000000, 0.000000, 1.000000]
  }
}
// create a sketch on the plane
sketch000 = startSketchOn(plane000)
// create a profile for the outer circle of the o-ring
outerCircleProfile = circle({center: [0.000000, 0.000000], radius: outerDiameter / 2}, sketch000, $arc000)
// create a profile for the inner circle of the o-ring
innerCircleProfile = circle({center: [0.000000, 0.000000], radius: innerDiameter / 2}, sketch000, $arc001)
// create a profile with holes sketch000Profile000Holes
oRingProfile = outerCircleProfile
  |> hole(innerCircleProfile, %)
// extrude the o-ring profile to create the o-ring
oRing = extrude(thickness, [oRingProfile])