// Generated by Text-to-CAD: rocket motor holder for I140W for AeroTech that uses o-ring
// Define constants in millimeters (mm)
motorDiameter = 38.0
holderOuterDiameter = 50.0
holderHeight = 100.0
oRingDiameter = 42.0
oRingThickness = 3.0
holderWallThickness = 5.0
// define a plane
plane000 = {
  plane: {
    origin: [0.000000, 0.000000, 0.000000],
    xAxis: [1.000000, 0.000000, 0.000000],
    yAxis: [0.000000, 1.000000, 0.000000],
    zAxis: [0.000000, 0.000000, 1.000000]
  }
}
// create a sketch for the holder on the plane
sketch000 = startSketchOn(plane000)
// create a profile for the holder
holderProfile = startProfileAt([holderOuterDiameter / 2, 0.000000], sketch000)
  |> line([0.000000, holderHeight], %, $line000)
  |> line([-holderWallThickness, 0.000000], %, $line001)
  |> line([0.000000, -holderHeight + oRingThickness], %, $line002)
  |> line([-oRingThickness, 0.000000], %, $line003)
  |> line([0.000000, -oRingThickness], %, $line004)
  |> line([holderWallThickness + oRingThickness, 0.000000], %, $line005)
  |> close(%)
// revolve the holder profile to create the holder
holder = revolve({axis: 'Y', angle: 360.000000}, holderProfile)
// create a sketch for the o-ring on the plane
sketch001 = startSketchOn(plane000)
// create a profile for the o-ring
oRingProfile = startProfileAt([oRingDiameter / 2, holderHeight - oRingThickness], sketch001)
  |> line([0.000000, oRingThickness], %, $line006)
  |> line([-oRingThickness, 0.000000], %, $line007)
  |> line([0.000000, -oRingThickness], %, $line008)
  |> line([oRingThickness, 0.000000], %, $line009)
  |> close(%)
// revolve the o-ring profile to create the o-ring
oRing = revolve({axis: 'Y', angle: 360.000000}, oRingProfile)